name: 🚀 deploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, windows-2022]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: 📥 Install CMake & Conan
        run: pip3 install cmake conan==2.0.6

      - name: 📡 Add `libhal-trunk` conan remote
        run: |
          conan remote add libhal-trunk https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: 📡 Create and setup default profile
        run: conan profile detect --force

      - name: 👁️‍🗨️ Show conan profile
        run: conan profile show

      - name: 📦 Create Conan Package
        working-directory: all
        run: conan create . --version=${{ inputs.version }} -b missing

      - name: 📡 Sign into JFrog Artifactory
        if: ${{ github.ref == 'refs/heads/main' && runner.os != 'Windows' }}
        env:
          API_KEY: ${{ secrets.JFROG_LIBHAL_TRUNK_API_KEY }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_USER }}
        run: conan remote login -p $API_KEY libhal-trunk $JFROG_USER

      - name: 📡 Sign into JFrog Artifactory (Powershell)
        if: ${{ github.ref == 'refs/heads/main' && runner.os == 'Windows' }}
        env:
          API_KEY: ${{ secrets.JFROG_LIBHAL_TRUNK_API_KEY }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_USER }}
        run: conan remote login -p $env:API_KEY libhal-trunk $env:JFROG_USER

      - name: 🆙 Upload package to `libhal-trunk` repo
        if: ${{ github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-22.04' }}
        run: |
          conan upload "clang-tidy/*" --only-recipe --confirm -r=libhal-trunk
